Database
Lukease/mishmash pull request #4
Opened 2022-06-13 11:39 UTC by Lukease

2022-06-13 12:35 UTC, jpudysz requested changes

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +import {renderProduct} from '../products_utils'
add spaces between `{}` in the entire project

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +import {ingredientData} from '../type/ingredient-data'
this is invalid import, add index.ts and export things.
Imports should be one level deep eg.:
```
import { ingredientData } from '../type'
```

Also file name should be probably `types`

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    const loader = $('<div>').addClass('products__loader').appendTo($('.products'))
It's a good practice to chain operations in the given way:
```
const loader = $('<div>')
     .addClass('products__loader')
     .appendTo($('.products'))
```

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    const url = 'http://localhost:3001/ingredients'
you can create a util function to append only the last part to the url. Localhost is mandatory so, you shouldn't repeat it multiple times

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +        method: 'GET'
GET is default value, you can use shorthand:
```
fetch(url)
```

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +        .catch(error => {
it will never go to the catch. I showed how to resolve it this morning on the whiteboard

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +            $('<div>').addClass('products__error').text(error).appendTo($('.loader-container')).css('color', 'red').css('font-size', '30px')
add enter for chaining

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    ingredientsArray.forEach((object) => {
no need for `()`

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +        $('.selected-product__text').attr('readOnly', 'true').css('text-align', 'center')
enters

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    const url: string = `http://localhost:3001/ingredients?ingredientsId=${ingredientId}`
aa

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +        .then((response) => response.json())
aa

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +        .then((response) => response.json())
aa

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    const url = 'http://localhost:3001/ingredients'
aa

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    const url = `http://localhost:3001/ingredients?ingredientName=${ingredientName}`
aa

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +        .then((response) => response.json())
aa

2022-06-13 12:35 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +}
given all the comments above, you can update every file to follow these rules

2022-06-14 10:31 UTC, jpudysz requested changes

2022-06-14 10:31 UTC, jpudysz commented on fetch-config.ts
> +export const baseUrl = 'http://localhost:3001/'
I can't see additional axios config

2022-06-14 10:31 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    await fetch(`${baseUrl}ingredients`)
it can be done better with axios global config

2022-06-14 10:31 UTC, jpudysz commented on http-client/ingredients-database_utils.ts
> +    ingredientsArray.forEach( object => {
remove space, also object is too generic, use more descriptive name

2022-06-14 10:31 UTC, jpudysz commented on http-client/recipes-database_utils.ts
> +        .then(async response => {
you can write it better:
```
fetch(...)
   .then(response => response.text())
   .then(recipes => recipesArray.concat(recipes))
```

2022-06-14 10:31 UTC, jpudysz commented on http-client/recipes-database_utils.ts
> +        .then(() => {
finally

2022-06-14 10:31 UTC, jpudysz commented on http-client/recipesIngredients-database_utils.ts
> +    return fetch(`${baseUrl}recipesIngredients/by-ingredients?ingredientsId=${ingredientsId}`)
use axios global config and fix these urls

2022-06-14 10:31 UTC, jpudysz commented on main.ts
> +import { getAllIngredients } from './http-client/ingredients-database_utils'
bad import

2022-06-14 10:31 UTC, jpudysz commented on mish_mash_utils.ts
> +import { getAllIngredients } from './http-client/ingredients-database_utils'
bad imports, add index.ts

2022-06-14 10:31 UTC, jpudysz commented on recipes_utils.ts
> +import { addNewRecipe, deleteRecipe, getAllRecipes, getOneRecipe } from './http-client/recipes-database_utils'
bad imports

2022-06-14 11:06 UTC, Lukease commented on http-client/recipesIngredients-database_utils.ts
> +    return fetch(`${baseUrl}recipesIngredients/by-ingredients?ingredientsId=${ingredientsId}`)
i cant config axios, every single time doesnt work

2022-06-14 11:12 UTC, jpudysz commented on http-client/recipesIngredients-database_utils.ts
> +    return fetch(`${baseUrl}recipesIngredients/by-ingredients?ingredientsId=${ingredientsId}`)
find a solution :) you can google it

2023-03-02 09:38 UTC, merged